import {randomUUID} from "node:crypto";
import {query} from "./index";
import type {Post,PostInput} from "../POSTS";
type Row={id:string;slug:string;title:string;summary:string;content:string;image:string|null;category:string;status:"draft"|"published"|"scheduled";publishedAt:string|null;scheduledAt:string|null;seoTitle:string|null;seoDescription:string|null;createdAt:string;updatedAt:string};
const select="SELECT id,slug,title,summary,content,image,category,status,published_at AS \"publishedAt\",scheduled_at AS \"scheduledAt\",seo_title AS \"seoTitle\",seo_description AS \"seoDescription\",created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM posts";
const map=(r:Row):Post=>({id:r.id,slug:r.slug,title:r.title,summary:r.summary,content:r.content,image:r.image||undefined,category:r.category,status:r.status,publishedAt:r.publishedAt||undefined,scheduledAt:r.scheduledAt||undefined,seoTitle:r.seoTitle||undefined,seoDescription:r.seoDescription||undefined,createdAt:r.createdAt,updatedAt:r.updatedAt});
function normalize(value:string){return value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,100)||"post";}
export async function readPosts(){return (await query<Row>(select+" ORDER BY created_at DESC")).map(map);}
export async function createPost(input:PostInput){const rows=await query<Row>("INSERT INTO posts(id,slug,title,summary,content,image,category,status,published_at,scheduled_at,seo_title,seo_description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,slug,title,summary,content,image,category,status,published_at AS \"publishedAt\",scheduled_at AS \"scheduledAt\",seo_title AS \"seoTitle\",seo_description AS \"seoDescription\",created_at AS \"createdAt\",updated_at AS \"updatedAt\"",[randomUUID(),normalize(input.slug||input.title),input.title,input.summary,input.content,input.image||null,input.category,input.status,input.status==="published"?new Date():null,input.scheduledAt||null,input.seoTitle||null,input.seoDescription||null]);return rows[0]?map(rows[0]):null;}
export async function updatePost(id:string,input:PostInput){const rows=await query<Row>("UPDATE posts SET slug=$1,title=$2,summary=$3,content=$4,image=$5,category=$6,status=$7,published_at=$8,scheduled_at=$9,seo_title=$10,seo_description=$11,updated_at=now() WHERE id=$12 RETURNING id,slug,title,summary,content,image,category,status,published_at AS \"publishedAt\",scheduled_at AS \"scheduledAt\",seo_title AS \"seoTitle\",seo_description AS \"seoDescription\",created_at AS \"createdAt\",updated_at AS \"updatedAt\"",[normalize(input.slug||input.title),input.title,input.summary,input.content,input.image||null,input.category,input.status,input.status==="published"?new Date():null,input.scheduledAt||null,input.seoTitle||null,input.seoDescription||null,id]);return rows[0]?map(rows[0]):null;}
export async function deletePost(id:string){const rows=await query<{id:string}>("DELETE FROM posts WHERE id=$1 RETURNING id",[id]);return rows.length>0;}
export async function readPublishedPosts(){return (await query<Row>(select+" WHERE (status='published' AND (published_at IS NULL OR published_at<=now())) OR (status='scheduled' AND scheduled_at IS NOT NULL AND scheduled_at<=now()) ORDER BY COALESCE(published_at,scheduled_at,updated_at) DESC")).map(map);}
export async function readPublishedPost(slug:string){const rows=await query<Row>(select+" WHERE slug=$1 AND ((status='published' AND (published_at IS NULL OR published_at<=now())) OR (status='scheduled' AND scheduled_at IS NOT NULL AND scheduled_at<=now())) LIMIT 1",[slug]);return rows[0]?map(rows[0]):null;}