import {createCipheriv,createDecipheriv,createHash,randomBytes,randomUUID} from "node:crypto";
import {query} from "./index";
import type {Webhook,WebhookEvent,Delivery} from "../WEBHOOKS";
const key=()=>{const s=(process.env.WEBHOOK_ENCRYPTION_KEY||"").trim();if(s.length<32)throw new Error("webhook_encryption_key_not_configured");return createHash("sha256").update(s).digest();};
const enc=(v:string)=>{const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",key(),iv);const b=Buffer.concat([c.update(v,"utf8"),c.final()]);return [iv.toString("base64url"),c.getAuthTag().toString("base64url"),b.toString("base64url")].join(".");};
const dec=(v:string)=>{const [i,t,d]=v.split(".");if(!i||!t||!d)throw new Error("encrypted_value_invalid");const c=createDecipheriv("aes-256-gcm",key(),Buffer.from(i,"base64url"));c.setAuthTag(Buffer.from(t,"base64url"));return Buffer.concat([c.update(Buffer.from(d,"base64url")),c.final()]).toString("utf8");};
type Row={id:string;name:string;url:string;method:"POST"|"PUT"|"PATCH";events:unknown;active:boolean;secretCiphertext:string;headersCiphertext:unknown;createdAt:string;updatedAt:string};
const toWebhook=(r:Row):Webhook=>({id:r.id,name:r.name,url:r.url,method:r.method,events:Array.isArray(r.events)?r.events.filter((x):x is WebhookEvent=>typeof x==="string"):[],active:r.active,secretConfigured:Boolean(r.secretCiphertext),headers:Object.keys(r.headersCiphertext&&typeof r.headersCiphertext==="object"?r.headersCiphertext as Record<string,unknown>:{}),createdAt:r.createdAt,updatedAt:r.updatedAt});
const select="SELECT id,name,url,method,events,active,secret_ciphertext AS \"secretCiphertext\",headers_ciphertext AS \"headersCiphertext\",created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM webhooks";
export async function readWebhooks(){return (await query<Row>(select+" ORDER BY created_at DESC")).map(toWebhook);}
export async function getStoredWebhook(id:string){const rows=await query<Row>(select+" WHERE id=$1 LIMIT 1",[id]);if(!rows[0])return null;const row=rows[0];const rawHeaders=row.headersCiphertext&&typeof row.headersCiphertext==="object"?row.headersCiphertext as Record<string,string>:{};return {...row,secret:row.secretCiphertext,headers:rawHeaders};}
export async function createWebhook(input:{name:string;url:string;method:"POST"|"PUT"|"PATCH";events:WebhookEvent[];active:boolean;secret:string;headers:Record<string,string>}){const rows=await query<Row>("INSERT INTO webhooks(id,name,url,method,events,active,secret_ciphertext,headers_ciphertext) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8::jsonb) RETURNING id,name,url,method,events,active,secret_ciphertext AS \"secretCiphertext\",headers_ciphertext AS \"headersCiphertext\",created_at AS \"createdAt\",updated_at AS \"updatedAt\"",[randomUUID(),input.name,input.url,input.method,JSON.stringify(input.events),input.active,enc(input.secret),JSON.stringify(Object.fromEntries(Object.entries(input.headers).map(([k,v])=>[k,enc(v)])))]);return toWebhook(rows[0]);}
export async function updateWebhook(id:string,input:{name:string;url:string;method:"POST"|"PUT"|"PATCH";events:WebhookEvent[];active:boolean;secret:string;headers:Record<string,string>}){const existing=await getStoredWebhook(id);if(!existing)return null;const secret=input.secret?enc(input.secret):existing.secret;const rows=await query<Row>("UPDATE webhooks SET name=$1,url=$2,method=$3,events=$4::jsonb,active=$5,secret_ciphertext=$6,headers_ciphertext=$7::jsonb,updated_at=now() WHERE id=$8 RETURNING id,name,url,method,events,active,secret_ciphertext AS \"secretCiphertext\",headers_ciphertext AS \"headersCiphertext\",created_at AS \"createdAt\",updated_at AS \"updatedAt\"",[input.name,input.url,input.method,JSON.stringify(input.events),input.active,secret,JSON.stringify(Object.fromEntries(Object.entries(input.headers).map(([k,v])=>[k,enc(v)]))),id]);return rows[0]?toWebhook(rows[0]):null;}
export async function deleteWebhook(id:string){const rows=await query<{id:string}>("DELETE FROM webhooks WHERE id=$1 RETURNING id",[id]);return rows.length>0;}
export async function readWebhookDeliveries(webhookId?:string){return query<Delivery>("SELECT id,webhook_id AS \"webhookId\",event,status,status_code AS \"statusCode\",duration_ms AS \"durationMs\",attempts,error,created_at AS at FROM webhook_deliveries WHERE ($1::uuid IS NULL OR webhook_id=$1) ORDER BY created_at DESC",[webhookId||null]);}
export async function recordDelivery(d:Delivery){await query("INSERT INTO webhook_deliveries(id,webhook_id,event,status,status_code,duration_ms,attempts,error) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[d.id,d.webhookId,d.event,d.status,d.statusCode||null,d.durationMs,d.attempts,d.error||null]);}
export function decryptSecret(v:string){return dec(v);}
