import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {allowAttempt,clientKey,validCsrf,validUserSession} from "@/Lib/SECURITY";
import {audit} from "@/Lib/AUDIT";
import {createTicket,readUserTickets} from "@/Lib/TICKETS";
import {dispatchWebhookEvent} from "@/Lib/WEBHOOKS";
import {parseJsonBody} from "@/Lib/BODY_LIMITS";
const maxBody=8_192;
const schema=z.object({subject:z.string().trim().min(3).max(160).refine(value=>!/[<>]/.test(value)),message:z.string().trim().min(5).max(5000).refine(value=>!/[<>]/.test(value))});
export async function GET(request:NextRequest){const userId=await validUserSession(request.cookies.get("shiny_user_session")?.value||"");if(!userId)return NextResponse.json({error:"authentication_required"},{status:401});if(!await allowAttempt("support-get:"+clientKey(request)+":"+userId,1000))return NextResponse.json({error:"rate_limited"},{status:429});return NextResponse.json({tickets:await readUserTickets(userId)},{headers:{"cache-control":"no-store"}});}
export async function POST(request:NextRequest){if(!await allowAttempt("support-create:"+clientKey(request),10000))return NextResponse.json({error:"rate_limited"},{status:429});const csrf=request.headers.get("x-csrf-token")||"";const stored=request.cookies.get("shiny_csrf")?.value||"";if(!csrf||csrf!==stored||!await validCsrf(csrf))return NextResponse.json({error:"invalid_csrf"},{status:403});const userId=await validUserSession(request.cookies.get("shiny_user_session")?.value||"");if(!userId)return NextResponse.json({error:"authentication_required"},{status:401});const body=await parseJsonBody(request,maxBody);if(!body.ok)return NextResponse.json({error:"invalid_input"},{status:body.reason==="too_large"?413:400});const parsed=schema.safeParse(body.data);if(!parsed.success)return NextResponse.json({error:"invalid_input"},{status:400});try{const ticket=await createTicket(userId,parsed.data.subject,parsed.data.message);if(!ticket)throw new Error("ticket_create_failed");await audit("ticket_created",request,{actor:userId,resource:ticket.id,result:"success"});void dispatchWebhookEvent("ticket.created",{ticketId:ticket.id,subject:ticket.subject},request).catch(()=>{});return NextResponse.json({ok:true,ticket},{status:201});}catch{await audit("ticket_create_failed",request,{actor:userId,result:"failure"});return NextResponse.json({error:"storage_error"},{status:500});}}
