import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {allowAttempt,clientKey,validAdminOwnerSession,validCsrf} from "@/Lib/SECURITY";
import {audit} from "@/Lib/AUDIT";
import {updateTicket} from "@/Lib/TICKETS";
import {parseJsonBody} from "@/Lib/BODY_LIMITS";
const maxBody=8_192;
const schema=z.object({status:z.enum(["open","in_progress","resolved"]),adminReply:z.string().max(5000).refine(value=>!/[<>]/.test(value)).optional().default("")});
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;if(!/^[A-Za-z0-9-]{20,100}$/.test(id))return NextResponse.json({error:"invalid_id"},{status:400});if(!await validAdminOwnerSession(request.cookies.get("shiny_admin_session")?.value||""))return NextResponse.json({error:"authentication_required"},{status:401});const csrf=request.headers.get("x-csrf-token")||"";const stored=request.cookies.get("shiny_csrf")?.value||"";if(!csrf||csrf!==stored||!await validCsrf(csrf))return NextResponse.json({error:"invalid_csrf"},{status:403});if(!await allowAttempt("admin-ticket:"+clientKey(request)+":"+id,1000))return NextResponse.json({error:"rate_limited"},{status:429});const body=await parseJsonBody(request,maxBody);if(!body.ok)return NextResponse.json({error:"invalid_input"},{status:body.reason==="too_large"?413:400});const parsed=schema.safeParse(body.data);if(!parsed.success)return NextResponse.json({error:"invalid_input"},{status:400});try{const ticket=await updateTicket(id,parsed.data.status,parsed.data.adminReply);if(!ticket)return NextResponse.json({error:"not_found"},{status:404});await audit("ticket_updated",request,{actor:(process.env.ADMIN_USER||"OWNER").trim()||"OWNER",resource:id,result:"success",status:ticket.status});return NextResponse.json({ok:true,ticket});}catch{await audit("ticket_update_failed",request,{actor:(process.env.ADMIN_USER||"OWNER").trim()||"OWNER",resource:id,result:"failure"});return NextResponse.json({error:"storage_error"},{status:500});}}
