"use client";
import {useEffect,useState} from "react";
type Ticket={id:string;subject:string;message:string;status:"open"|"in_progress"|"resolved";adminReply?:string;createdAt:string;updatedAt:string};
export default function Support(){
  const [tickets,setTickets]=useState<Ticket[]>([]);const [authenticated,setAuthenticated]=useState<boolean|null>(null);const [subject,setSubject]=useState("");const [message,setMessage]=useState("");const [sending,setSending]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>{fetch("/Api/Support",{credentials:"same-origin",cache:"no-store"}).then(async response=>{const data=await response.json().catch(()=>({}));if(response.ok){setAuthenticated(true);setTickets(Array.isArray(data.tickets)?data.tickets:[]);}else setAuthenticated(false)}).catch(()=>setAuthenticated(false))},[]);
  async function submit(event:React.FormEvent){event.preventDefault();if(sending)return;if(!subject.trim()||!message.trim()){setNotice("Preencha assunto e mensagem.");return;}setSending(true);setNotice("");try{const csrf=await fetch("/Api/Csrf",{credentials:"same-origin",cache:"no-store"}).then(response=>response.json());const response=await fetch("/Api/Support",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":csrf.token},body:JSON.stringify({subject,message})});const data=await response.json().catch(()=>({}));if(!response.ok){setNotice(data.error==="rate_limited"?"Aguarde antes de abrir outro ticket.":"Não foi possível abrir o ticket.");return;}setTickets(current=>[data.ticket,...current]);setSubject("");setMessage("");setNotice("Ticket enviado.");}catch{setNotice("Não foi possível conectar ao suporte.");}finally{setSending(false);}}
  return <main className="public-support-page"><header className="public-news-header"><a href="/">SHINY STORE</a><span>SUPORTE</span></header><section className="public-support-content"><p className="vault2-kicker">SHINY / SUPPORT</p><h1>Suporte</h1><p className="public-support-lead">Abra um ticket para acompanhar uma dúvida de compra, entrega ou acesso.</p>{authenticated===false?<div className="public-support-empty"><strong>Entre na sua conta</strong><p>O suporte por ticket exige uma sessão de usuário autenticada.</p><a href="/">Voltar para a loja</a></div>:<div className="public-support-grid"><form className="public-support-form" onSubmit={submit}><label>Assunto<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={160}/></label><label>Mensagem<textarea rows={9} value={message} onChange={e=>setMessage(e.target.value)} maxLength={5000}/></label><button disabled={sending}>{sending?"Enviando…":"Enviar ticket"}</button>{notice&&<p role="status">{notice}</p>}</form><div className="public-support-tickets"><h2>Seus tickets</h2>{tickets.length?tickets.map(ticket=><article key={ticket.id}><div><strong>{ticket.subject}</strong><span>{ticket.status==="open"?"Aberto":ticket.status==="in_progress"?"Em atendimento":"Resolvido"}</span></div><p>{ticket.message}</p>{ticket.adminReply&&<blockquote>{ticket.adminReply}</blockquote>}</article>):<p className="vault2-muted">Nenhum ticket aberto.</p>}</div></div>}</section></main>;
}
