import {NextRequest,NextResponse} from "next/server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {allowAttempt,clientKey,validAdminOwnerSession,validCsrf} from "@/Lib/SECURITY";
import {audit} from "@/Lib/AUDIT";
import {deletePost,readPosts,updatePost} from "@/Lib/POSTS";
import {dispatchWebhookEvent} from "@/Lib/WEBHOOKS";
import {parseJsonBody} from "@/Lib/BODY_LIMITS";

const maxBody=65_536;
const text=z.string().trim().refine(value=>!/[<>]/.test(value),{message:"html_not_allowed"});
const schema=z.object({title:text.min(1).max(180),slug:z.string().trim().max(100).regex(/^[A-Za-z0-9-]*$/),summary:text.max(500),content:text.min(1).max(30000),image:z.string().trim().max(500).refine(value=>value===""||value.startsWith("/")||/^https:\/\//i.test(value),{message:"image_url_invalid"}).optional().default(""),category:text.max(80),status:z.enum(["draft","published","scheduled"]),scheduledAt:z.string().datetime({offset:true}).optional().or(z.literal("")),seoTitle:text.max(180).optional().or(z.literal("")),seoDescription:text.max(300).optional().or(z.literal(""))}).superRefine((value,ctx)=>{if(value.status==="scheduled"&&!value.scheduledAt)ctx.addIssue({code:"custom",path:["scheduledAt"],message:"schedule_required"});});
function actor(){return (process.env.ADMIN_USER||"OWNER").trim()||"OWNER";}
async function auth(request:NextRequest,mutation=false){if(!await validAdminOwnerSession(request.cookies.get("shiny_admin_session")?.value||""))return "authentication_required";if(mutation){const csrf=request.headers.get("x-csrf-token")||"";const stored=request.cookies.get("shiny_csrf")?.value||"";if(!csrf||csrf!==stored||!await validCsrf(csrf))return "invalid_csrf";}return null;}
async function rate(request:NextRequest,id:string){return !await allowAttempt("admin-post:"+clientKey(request)+":"+id,1000);}
export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;if(!/^[A-Za-z0-9_-]{1,100}$/.test(id))return NextResponse.json({error:"invalid_id"},{status:400});const denied=await auth(request);if(denied)return NextResponse.json({error:denied},{status:401});if(await rate(request,id))return NextResponse.json({error:"rate_limited"},{status:429});const post=(await readPosts()).find(item=>item.id===id);return post?NextResponse.json({post}):NextResponse.json({error:"not_found"},{status:404});}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const denied=await auth(request,true);if(denied)return NextResponse.json({error:denied},{status:denied==="invalid_csrf"?403:401});if(await rate(request,id))return NextResponse.json({error:"rate_limited"},{status:429});const body=await parseJsonBody(request,maxBody);if(!body.ok)return NextResponse.json({error:"invalid_input"},{status:body.reason==="too_large"?413:400});const parsed=schema.safeParse(body.data);if(!parsed.success)return NextResponse.json({error:"invalid_input"},{status:400});try{const before=(await readPosts()).find(item=>item.id===id);if(!before)return NextResponse.json({error:"not_found"},{status:404});const post=await updatePost(id,{...parsed.data,scheduledAt:parsed.data.scheduledAt||undefined});if(post==="duplicate_slug")return NextResponse.json({error:"duplicate_slug"},{status:409});if(!post)return NextResponse.json({error:"not_found"},{status:404});revalidatePath("/News");revalidatePath("/News/"+before.slug);revalidatePath("/News/"+post.slug);await audit("admin_post_updated",request,{actor:actor(),resource:id,result:"success",status:post.status});if(post.status==="published"&&before.status!=="published")void dispatchWebhookEvent("post.created",{postId:post.id,slug:post.slug,title:post.title},request).catch(()=>{});return NextResponse.json({ok:true,post});}catch{await audit("admin_post_update_failed",request,{actor:actor(),resource:id,result:"storage_error"});return NextResponse.json({error:"storage_error"},{status:500});}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const denied=await auth(request,true);if(denied)return NextResponse.json({error:denied},{status:denied==="invalid_csrf"?403:401});if(await rate(request,id))return NextResponse.json({error:"rate_limited"},{status:429});try{const before=(await readPosts()).find(item=>item.id===id);if(!before)return NextResponse.json({error:"not_found"},{status:404});const deleted=await deletePost(id);if(!deleted)return NextResponse.json({error:"not_found"},{status:404});revalidatePath("/News");revalidatePath("/News/"+before.slug);await audit("admin_post_deleted",request,{actor:actor(),resource:id,result:"success"});return NextResponse.json({ok:true});}catch{await audit("admin_post_delete_failed",request,{actor:actor(),resource:id,result:"storage_error"});return NextResponse.json({error:"storage_error"},{status:500});}}
