import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {allowAttempt,clientKey,validAdminOwnerSession,validCsrf} from "@/Lib/SECURITY";
import {audit} from "@/Lib/AUDIT";
import {deleteFaq,readFaq,updateFaq} from "@/Lib/FAQ";
import {parseJsonBody} from "@/Lib/BODY_LIMITS";
const maxBody=16_384;
const text=z.string().trim().min(1).max(500).refine(value=>!/[<>]/.test(value));
const schema=z.object({question:text,answer:z.string().trim().min(1).max(5000).refine(value=>!/[<>]/.test(value)),category:text.max(80),active:z.boolean(),order:z.number().int().min(0).max(100000)});
function actor(){return (process.env.ADMIN_USER||"OWNER").trim()||"OWNER";}async function auth(request:NextRequest,mutation=false){if(!await validAdminOwnerSession(request.cookies.get("shiny_admin_session")?.value||""))return "authentication_required";if(mutation){const csrf=request.headers.get("x-csrf-token")||"";const stored=request.cookies.get("shiny_csrf")?.value||"";if(!csrf||csrf!==stored||!await validCsrf(csrf))return "invalid_csrf";}return null;}async function rate(request:NextRequest,id:string){return !await allowAttempt("admin-faq:"+clientKey(request)+":"+id,1000);}
export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const denied=await auth(request);if(denied)return NextResponse.json({error:denied},{status:401});if(await rate(request,id))return NextResponse.json({error:"rate_limited"},{status:429});const faq=(await readFaq()).find(item=>item.id===id);return faq?NextResponse.json({faq}):NextResponse.json({error:"not_found"},{status:404});}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const denied=await auth(request,true);if(denied)return NextResponse.json({error:denied},{status:denied==="invalid_csrf"?403:401});if(await rate(request,id))return NextResponse.json({error:"rate_limited"},{status:429});const body=await parseJsonBody(request,maxBody);if(!body.ok)return NextResponse.json({error:"invalid_input"},{status:body.reason==="too_large"?413:400});const parsed=schema.safeParse(body.data);if(!parsed.success)return NextResponse.json({error:"invalid_input"},{status:400});try{const faq=await updateFaq(id,parsed.data);if(!faq)return NextResponse.json({error:"not_found"},{status:404});await audit("admin_faq_updated",request,{actor:actor(),resource:id,result:"success"});return NextResponse.json({ok:true,faq});}catch{await audit("admin_faq_update_failed",request,{actor:actor(),resource:id,result:"failure"});return NextResponse.json({error:"storage_error"},{status:500});}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const denied=await auth(request,true);if(denied)return NextResponse.json({error:denied},{status:denied==="invalid_csrf"?403:401});if(await rate(request,id))return NextResponse.json({error:"rate_limited"},{status:429});try{const deleted=await deleteFaq(id);if(!deleted)return NextResponse.json({error:"not_found"},{status:404});await audit("admin_faq_deleted",request,{actor:actor(),resource:id,result:"success"});return NextResponse.json({ok:true});}catch{await audit("admin_faq_delete_failed",request,{actor:actor(),resource:id,result:"failure"});return NextResponse.json({error:"storage_error"},{status:500});}}
